### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by samsmith** [fix-macosx/fix-macosx#1]
It may be worth referencing the buried text from the system preferences -> spotlight -> "about spotlight suggestions and privacy" button:

"If you do not want your Spotlight search queries and Spotlight Suggestions usage data sent to Apple, you can turn off Spotlight Suggestions. Simply deselect the checkboxes for both Spotlight Suggestions and Bing Web Searches in the Search Results tab in the Spotlight preference pane found within System Preferences on your Mac. If you turn off Spotlight Suggestions and Bing Web Searches, Spotlight will search the contents of only your Mac."

and the equivalent for location services (are those settable via a script?)

**Comment by landonf** [comment]
Good call. If anyone wants to claim this issue, I'm happy to accept the addition of some manual instructions; otherwise I'll take a look at doing this later this evening.

**Comment by landonf** [comment]
This info is now included in the sidebar. Thanks!
