### ISSUE TITLE
iCloud Uploads Local Data Outside of iCloud Drive

### ISSUE THREAD

**Issue by couto** [fix-macosx/fix-macosx#6]
This blog post was recently published: http://datavibe.net/~sneak/20141023/wtf-icloud/

I'm just sharing this to increase awareness of this problem. while, personally, I think this is in the scope of this project, I trust you can do a better judgment of that.

Feel free to close this issue, if you feel this is irrelevant.

**Comment by landonf** [comment]
Thanks; I also verified this locally via net-monitor. I believe we'll have to expand the website to allow more detailed documentation on iCloud issues (and more)

**Comment by sneak** [comment]
Hi, commenting here (I'm the blog post author) to track the issue.
